### ISSUE TITLE
Uom should be a LocalizedFieldContainer

### ISSUE THREAD

**Issue by brunoamacos** [opencrx/opencrx#117]
It makes no sense for SI units like m or kg. But for some custom Uom's like load, unit, barril or bag we need translations.

**Comment by wfro64** [comment]
Uom is a DescriptionContainer which allows to add language-specific description and detailedDescriptions:

![grafik](https://user-images.githubusercontent.com/11387061/203935747-cf190cb0-caab-496d-b019-212c23200c26.png)

![grafik](https://user-images.githubusercontent.com/11387061/203936192-b7b183eb-bc91-441a-b1a8-6111fe0ed6c2.png)

Since a Uom does not have more fields than description and detailedDescription a LocalizedFieldCointainer seems to be overkill. 

Note: LocalizedFieldCointainer was introduced to "localize" CrxObjects and all of its sub-classes.
